### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by dscorbett** [AlexKnauth/measures-with-dimensions#4]
`farrad` should be `farad`. `gigaeloctron-volt/c^2` should be `gigaelectron-volt/c^2`. `celcius:` should be `celsius:`.

**Comment by AlexKnauth** [comment]
Thanks! Those have now now been fixed with https://github.com/AlexKnauth/measures-with-dimensions/commit/3658c29d2d6ba0b2dcff137e316c14cc82c26a65 and https://github.com/AlexKnauth/measures-with-dimensions/commit/68c057568c9a431f1ad054aaaefe3c6f65304365.

**Comment by dscorbett** [comment]
You left `celcius:`. Was that intentional?

**Comment by AlexKnauth** [comment]
No, I forgot, but that's fixed now in https://github.com/AlexKnauth/measures-with-dimensions/commit/d70218bb051579863b2f186e7a27426c4ea5c493.
